### ISSUE TITLE
Store player data

### ISSUE THREAD

**Issue by LahiruRajapaksha** [LahiruRajapaksha/game-dev#31]
## Tasks
- [ ] Add firestore connection
- [ ] Add player main data
- [ ] Add player game level data
